services:
  postgres:
    container_name: synapse_DB
    image: postgres:18
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: synapse_DB
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - synapse-network
    restart: unless-stopped
networks :
  synapse-network :
    driver: bridge

volumes:
  postgres :
